title: "Alexander Bogomolny: All about me"
author: "Alexander Bogomolny"
email: "alexandernjd@gmail.com"
theme: jekyll-theme-cayman
description: > # this means to ignore newlines until "baseurl:"
  I am from East Brunswick, New Jersey.
  I am currently a Senior at East Brunswick High School and plan on attending Rutgers Business School- New Brunswick in Fall of 2020
  I have my own podcast available on most platforms called Bogocast.
  This podcast studies people from my town and how their surroundings helped shape them into the person they are today.
  I am a state finalist for Future Business Leaders of America, I played Varsity Football for the school team, and I am the captain of the East Brunswick Soccer Club U-18 Travel Team, and am a former Chess State Champion. 
  I have over 200 volunteer hours that range from an adult day care to helping special needs swim.
  I try to be the best person I can be and I hope you enjoy my web page :)

# social links
twitter_username: "alexbogomolny" # DO NOT include the @ character, or else the build will fail!
github_username:  "alexbogomolny" # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
